In [1]:
# 1st Numpy

# install numpy by
pip install numpy

TYPES:-
1.single dimensional array 
2.two  dimensional array [rows & columns]
3.multi dimensional array [mariex]

In [2]:
#single dimensional array
import numpy as np
d1_arr=np.array([1,2,3,4,5,6])
print(d1_arr)

[1 2 3 4 5 6]


In [3]:
# two dimensional array
import numpy as np
d1_arr=np.array([[1,2,3],
                  [4,5,6]])
print(d1_arr)

[[1 2 3]
 [4 5 6]]


In [4]:
# multi dimensional array  *matriex

import numpy as np
matriex=np.array([[1,2,3],
                  [4,5,6]])
print(matriex)

[[1 2 3]
 [4 5 6]]


python list to create array


In [ ]:
import numpy as np

In [7]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
#print zeros

zeros=np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [10]:
# print 1s
# we can print as tapals

ones=np.ones((1,5))  #1row &5 colums od ones
print(ones)

[[1. 1. 1. 1. 1.]]


In [13]:
#to add specific value  (full)

full_array=np.full((2,5),3)
print(full_array)

[[3 3 3 3 3]
 [3 3 3 3 3]]


creating sequence of number 
it's as like 'range' function of python
but we use 'arange()'   # arange(start,stop,step)

In [14]:
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [18]:
#identity matriex   by eye
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
