# numpy methods
1. sort()
2. sum()
3. prod()
4. min()
5. max()
6. 
   

In [19]:
# sort 
import numpy as np
arr = np.array((3,2,4,1))
arr.sort()
print(arr)

[1 2 3 4]


In [24]:

# sum
arr.sum()


np.int64(10)

In [26]:

# product
arr.prod()


np.int64(24)

In [30]:

# mean
arr.mean()   # this case 10/4


np.float64(2.5)

In [33]:

#max
arr.max()  # maximum  number of arr


np.int64(4)

In [37]:

#argmax
arr.argmax()  # prints maximum index number 


np.int64(3)

In [40]:

arr.cumsum()  # Cumulative sum of the elements of arr


array([ 1,  3,  6, 10])

In [48]:

# cumprod()
arr.cumprod()     # Cumulative  productof the elements of arr


array([1, 2, 3, 4])

#var()      Variance in Python with NumPy is a measure of how much the elements in an array differ from the mean of the array. 


Compute the mean:
(3 + 2 + 4 + 1) / 4 = 10 / 4 = 2.5

Find squared differences from the mean:

(3 - 2.5)² = 0.25

(2 - 2.5)² = 0.25

(4 - 2.5)² = 2.25

(1 - 2.5)² = 2.25

Sum these squared differences:
0.25 + 0.25 + 2.25 + 2.25 = 5

Divide by number of elements (N = 4):
5 / 4 = 1.25

In [49]:
arr.var()

np.float64(1.25)

In [51]:
# std()              Standard deviation
arr.std()

np.float64(1.118033988749895)

In [56]:

arr.shape = (2,2)
arr.T                              # Equivalent to a.transpose()

array([[1, 3],
       [2, 4]])